# Generated by Django 3.2.8 on 2021-10-11 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_niveau_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='niveau',
            table='Niveau',
        ),
    ]
