# Generated by Django 3.2.8 on 2021-10-11 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_niveau_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='niveau',
            table=None,
        ),
    ]
