# Generated by Django 3.2.8 on 2021-10-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_niveau_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logement',
            fields=[
                ('id', models.AutoField(db_column='idLo', primary_key=True, serialize=False)),
                ('lib', models.CharField(db_column='libLo', max_length=200)),
                ('detail', models.TextField(db_column='detailLo')),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='lo_createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='lo_updatedAt')),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.AutoField(db_column='idV', primary_key=True, serialize=False)),
                ('lib', models.CharField(db_column='nomV', max_length=200)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='v_createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='v_updatedAt')),
            ],
        ),
    ]
