# Generated by Django 3.2.8 on 2021-10-13 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0006_auto_20211012_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debouche',
            fields=[
                ('id', models.AutoField(db_column='idDeb', primary_key=True, serialize=False)),
                ('lib', models.CharField(db_column='libDeb', max_length=200)),
                ('detail', models.TextField(db_column='detailDeb')),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='deb_createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='deb_updatedAt')),
            ],
            options={
                'ordering': ['lib'],
            },
        ),
        migrations.AlterModelOptions(
            name='logement',
            options={'ordering': ['-updatedAt']},
        ),
        migrations.AlterField(
            model_name='logement',
            name='user',
            field=models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='logement',
            name='ville',
            field=models.ForeignKey(db_column='idV', on_delete=django.db.models.deletion.DO_NOTHING, to='base.ville'),
        ),
        migrations.CreateModel(
            name='Metier',
            fields=[
                ('id', models.AutoField(db_column='idM', primary_key=True, serialize=False)),
                ('debouche', models.ForeignKey(db_column='idDeb', on_delete=django.db.models.deletion.DO_NOTHING, to='base.debouche')),
                ('niveau', models.ForeignKey(db_column='idNiv', on_delete=django.db.models.deletion.DO_NOTHING, to='base.niveau')),
            ],
        ),
    ]
