# Generated by Django 3.2.8 on 2021-10-13 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20211013_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='niveau',
            options={'ordering': ['lib']},
        ),
        migrations.AddField(
            model_name='niveau',
            name='detail',
            field=models.TextField(blank=True, db_column='detailNiv', null=True),
        ),
        migrations.AlterField(
            model_name='metier',
            name='debouche',
            field=models.ForeignKey(db_column='idDeb', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Metier', to='base.debouche'),
        ),
        migrations.AlterField(
            model_name='metier',
            name='niveau',
            field=models.ForeignKey(db_column='idNiv', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Metier', to='base.niveau'),
        ),
    ]
