# Generated by Django 3.2.8 on 2021-10-17 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20211013_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.AutoField(db_column='idEc', primary_key=True, serialize=False)),
                ('lib', models.CharField(db_column='nomEc', max_length=200)),
                ('adr', models.CharField(db_column='adrEc', max_length=200)),
                ('phone', models.CharField(db_column='phoneEc', max_length=100)),
                ('email', models.EmailField(db_column='emailEc', max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='ec_createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='ec_updatedAt')),
                ('deactivatedAt', models.DateTimeField(blank=True, db_column='ec_deactivatedAt', null=True)),
                ('formations', models.ManyToManyField(blank=True, related_name='Formations', to='base.Niveau')),
                ('ville', models.ForeignKey(db_column='idV', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Ecoles', to='base.ville')),
            ],
        ),
    ]
