# Generated by Django 3.2.8 on 2021-10-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_ecole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecole',
            name='formations',
            field=models.ManyToManyField(blank=True, db_table='Former', related_name='Formations', to='base.Niveau'),
        ),
    ]
