# Generated by Django 3.2.8 on 2021-10-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_ecole_formations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecole',
            name='formations',
            field=models.ManyToManyField(blank=True, related_name='Formations', to='base.Niveau'),
        ),
    ]
