# Generated by Django 3.2.8 on 2021-10-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(db_column='accountId', primary_key=True, serialize=False)),
                ('email', models.EmailField(db_column='email', max_length=100, unique=True)),
                ('pwd', models.TextField(db_column='password', max_length=250)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='ac_createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='ac_updatedAt')),
            ],
        ),
    ]
